### ISSUE TITLE
Cannot connect to Database (keepassxc-browser, Chromium, Arch Linux)

### ISSUE THREAD

**Issue by andreas-h** [varjolintu/keepassxc#10]
Not sure which repo to report this to, please apologize if this is the wrong one.

I have the *keepassxc-browser-git* package installed from AUR. In the "Debug Info" box of KeePassXC 2.2.0, it says "Revision ea23f95117ac035df18b47d31b204c95ab788252".  I installed the *keepasxc-browser* plugin into Chromium 61.0.3163.100.

## Expected Behavior

In the keepassxc-browser settings, my opened database should show up in "Connected Databases"

## Current Behavior

It shows "No connected databases found"

## Steps to Reproduce (for bugs)
1. Start `keepassxc`
2. Unlock database
3. In "Application settings", enable "Enable KeepassXC browser extension"
4. In "Supported Browsers" check "Chromium"
5. Click "Apply", then "OK"
6. In Chromium, go to the keepassxc-browser setting, click on "Connected Databases" tab
7. Click "Connect"

## Context
I want to access my database's contents from Chromium via keepassxc-browser.

## Debug Info
- KeePassXC - Version 2.2.0
- Revision: ea23f95117ac035df18b47d31b204c95ab788252

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Arch Linux
- CPU architecture: x86_64
- Kernel: linux 4.13.7-1-zen

Enabled extensions:
- Auto-Type
- YubiKey
- Native Messaging browser extension

**Comment by varjolintu** [comment]
Could you try to download the latest keepassxc-browser sources from the develop branch and load it as a temporary extension?

There could be some problems with the AUR package because it always takes the latest sources which might not be fully compatible with the latest released browser extension. So if you want to use the development-AUR, please use also development version of the keepassxc-browser.

**Comment by andreas-h** [comment]
Yes, thanks, that was it.

For someone who doesn't know anything about Chrome extensions:

1. I kept the keepassxc-browser extension installed
2. I downloaded the keepassxc-browser repository
3. Inside that working copy, I executed `./install.sh`

**Comment by varjolintu** [comment]
I think the install script is not even needed. The extension reads the same JSON file in spite of the version loaded.

**Comment by andreas-h** [comment]
Oh, but I don't know anything about Chrome extensions.  So when I just 
download the repo anywhere, how should Chrome know about it?

**Comment by varjolintu** [comment]
The browser extension code tells what JSON file to load from the browser's Native Messaging folder. The install script just installs the JSON file and points it to the KeePassXC binary. That should be already working because the error messages you've seen tells me there's a connection.

**Comment by schiessle** [comment]
Not sure if it is the same issue. But I also can't connect to KeepassXC. I use the AppImage of KeePassXC 2.2.0-browser-rc6 from here https://github.com/varjolintu/keepassxc/releases and the Firefox browser plugin from here https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/. But the toolbar icon always indicates that it is not connected., If I click on the toolbar icon and then "reload" I get a system notification "KeePassXC ready" and KeePassXC is moved to the foreground but nothing else happens. "Enable KeepassXC browser extension" is enabled and "Firefox" is checked under "Supported Browsers". Firefox version is Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by varjolintu** [comment]
I'm pretty sure that if you use an AppImage native messaging cannot connect to the binary because it doesn't know it's location before the start. If proxy is enabled the path to binaries are known but Unix domain sockets won't work without extra configuring.

For now, I suggest you compile the sources by yourself and try it that way.
