### ISSUE TITLE
Confirm access dialog prompts twice on page load

### ISSUE THREAD

**Issue by Isles487** [varjolintu/keepassxc#11]
## Expected Behavior
The confirm access dialog should prompt once when a page with username/password fields is loaded.

## Current Behavior
The confirm access dialog prompts twice, on on top of the other. This happens on firefox and chromium.

## Possible Solution

Not sure, but this does not occur once the page has already been loaded and I leave the tab, and then switch back to the tab. In that event, I am only prompted to confirm access once!

## Steps to Reproduce (for bugs)
1. Open a database in keepassxc
2. Connect to keepassxc with or without the proxy application 
3. Load a website for which credentials are stored in the database and for which you have not confirmed access and chosen "remember decision." For example, www.bankofamerica.com

## Context
Loading web pages with credentials.

## Debug Info

KeePassXC - Version 2.2.0
Revision: 3369702544040358eaeef58abbbcec714bbfdb12

KeepassXC-browser 0.3.9 extension on chromium

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- Native Messaging browser extension

**Comment by varjolintu** [comment]
Thanks for reporting this. Will be fixed.

**Comment by varjolintu** [comment]
And it seems this is Windows only.

**Comment by varjolintu** [comment]
Pushing in the fix today.
