### ISSUE TITLE
keepassxc overwrites the nativemessaging manifest files that it creates.

### ISSUE THREAD

**Issue by Isles487** [varjolintu/keepassxc#12]
When NativeMessaging is enabled in the KeePassXC options, and "supported browsers" is checked, each time settings are applied, the manifest files at C:\Users\<USER>\AppData\Local\keepassxc are overwritten to point to the executable path.

## Expected Behavior
I think that the manifests should remain the same if modified by the user - I've modified them to point to keepassxc-proxy instead of the keepassxc.exe file.

## Current Behavior
The manifests are overwritten to point to the keepass.exe path.

## Possible Solution
Maybe KeePassXC can have a separate option to generate the manifests automatically if they are not present? That way if a user does not know how to create the registry keys and the manifests the program will generate the files, but not overwrite them if they are already present.

## Steps to Reproduce (for bugs)

1.Enable NativeMessaging in KeepassXC
2.  Edit the manifest files at C:\Users\<USER>\AppData\Local\keepassxc for any browser to point to the proxy application (or any other custom path).
3.  Click "apply" 
4. Manifest files are overwritten to default.

## Context
I was trying to be load keepassxc-proxy instead of the kasspass.exe executable.

## Debug Info

KeePassXC - Version 2.2.0
Revision: 3369702544040358eaeef58abbbcec714bbfdb12

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- Native Messaging browser extension

**Comment by varjolintu** [comment]
The RC5 version already has this option in the Advanced tab in the Browser Extension settings.
From there you can:
- Enable/disable automatic updating of the binary location. If you are checked as a proxy user, the proxy location is updated
- Use a custom proxy with your own location, which is updated automatically to the JSON scripts if you have checked the option described above

**Comment by Isles487** [comment]
Thank you for letting me know - I don't know if I should open a new bug for this, but if I use a custom path it creates a firefox manifest that uses `\\` as the separator between directories. Firefox doesn't seem to like this.

**Comment by varjolintu** [comment]
If you are under Windows this is the correct behaviour. The default path is also written with `\\` separators. So what exactly happens?

**Comment by Isles487** [comment]
I must have done something wrong - seems to work fine.

**Comment by varjolintu** [comment]
Closing the ticket for now. Will reopen it if you still have the issue for some reason.
