### ISSUE TITLE
Enable proxy by default when "KeePass XC browser extension" is enabled

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc#14]
The proxy application should be used by default when the user checks the "Enable KeePassXC browser extension" checkbox in the settings. I think it would be very unexpected for users to find out that KeePassXC must not be running before they are launching the browser or that KeePassXC would quit when the browser is closed.

## Expected Behavior
KeePassXC and the user's browser are independent applications. Closing or launching one application does not close or launch the other. No unsaved data is lost when the browser is closed. KeePass-credentials can be used from multiple browsers running simultaneously.

## Current Behavior
The browser extension does not work if KeePassXC is running before the browser is started.
KeePassXC launches and quits with the browser.
Unsaved data may be lost when the browser is closed.

## Possible Solution
Enable the "Enable support for proxy application between KeePassXC and the browser extension" by default.

## Context
I think the browser extension is great, but it would vastly improve the usability to use the proxy by default. If the proxy is enabled, it works just like expected.

**Comment by varjolintu** [comment]
I agree with this. And actually this was the next item in my TODO list. So fixing it really soon.
