### ISSUE TITLE
Cannot use keepassxc-browser as Native Messaging browser extension plugin is not present in snap packaged version

### ISSUE THREAD

**Issue by richardfleming** [varjolintu/keepassxc#15]
## Expected Behavior

Expected to be able to turn on native message support in the snap packaged version.

## Current Behavior

Native messaging support is not available to enable.  The option is missing, with only KeePassHTTP being the only option.

## Steps to Reproduce (for bugs)

1. Install KeePassXC from Ubuntu store as snap (2.2.3)
2. Create/load a database and go to settings and try to enable native messaging support
3. scratch your head in wonder as the option isn't there?
4.

## Context

Can't use native browser plugin with native keepassxc app to get passwords in browser as plugin is missing.

## Debug Info

KeePassXC - Version 2.2.3
Revision: cf94610
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-19-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by varjolintu** [comment]
Again, this feature is not yet available in the public releases.
