### ISSUE TITLE
Proxy does not work on MacOS

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc#16]
## Expected Behavior
KeePassXC-Browser is able to start keepassxc-proxy and connect to the database.

## Current Behavior
KeePassXC-Browser is unable to connect to the database when the proxy is enabled ("timeout or not connected to KeePassXC").
The configuration in com.varjolintu.keepassxc_browser.json is correct and points to the proxy binary in /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy.
When starting the proxy directly from this directory, the following error is displayed in the terminal:

/Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy ; exit;
dyld: Library not loaded: /usr/local/opt/qt/lib/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
  Reason: image not found
fish: '/Applications/KeePassXC.app/Con…' terminated by signal SIGABRT (Abort)

There is no folder named "qt" in /usr/local/opt/.

## Possible Solution
Change the linking for the Qt-library or include it in the proxy binary.

## Debug Info
KeePassXC - Version 2.2.4
Revision: 7350ff7

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.1

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- Native messaging browser extension

**Comment by varjolintu** [comment]
I wonder if it has something to do with the Qt 5.10 update. I'll try to find the cause but currently I am not able to reproduce the issue.

**Comment by varjolintu** [comment]
Fixed with https://github.com/varjolintu/keepassxc/commit/63f04db993784c44620356c8e030135d9eb532e8. New .dmg is uploaded to the release. Please test it out.

**Comment by whisdol** [comment]
Works, thanks!
