### ISSUE TITLE
Merge the Following SSH-Agent Extension

### ISSUE THREAD

**Issue by iceman73** [varjolintu/keepassxc#18]
Would like to see the following extension merged from Keepassxc

https://github.com/keepassxreboot/keepassxc/pull/1098

**Comment by varjolintu** [comment]
Sorry, but it's not going to be merged to my fork. These branches are based on the upstream develop branch, so there's some support with the [keepassxc-browser](https://github.com/varjolintu/keepassxc/tree/keepassxc-browser) branch but you have to compile it by yourself.
