### ISSUE TITLE
Compiling from Source Getting Error on browser not defined

### ISSUE THREAD

**Issue by iceman73** [varjolintu/keepassxc#19]
When compiling from source I get the following error stating that 'browser' [-Werror=unused-parameter], and therefore preventing compiliation

`[ 35%] Building CXX object src/browser/CMakeFiles/keepassxcbrowser.dir/HostInstaller.cpp.obj
C:/msys64/home/cstocker/download/keepassxc/src/browser/HostInstaller.cpp: In member function 'QString HostInstaller::getInstallDir(HostInstaller::SupportedBrowsers) const':
C:/msys64/home/cstocker/download/keepassxc/src/browser/HostInstaller.cpp:152:56  error: unused parameter 'browser' [-Werror=unused-parameter]
 QString HostInstaller::getInstallDir(SupportedBrowsers browser) const
                                                        ^~~~~~~
cc1plus.exe: all warnings being treated as errors
make[2]: *** [src/browser/CMakeFiles/keepassxcbrowser.dir/build.make:231: src/browser/CMakeFiles/keepassxcbrowser.dir/HostInstaller.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:607: src/browser/CMakeFiles/keepassxcbrowser.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
`

## Expected Behavior
Expect that compilation should not error on this function as its important for the browsr extension to work.

## Current Behavior
The following error is seen
`[ 35%] Building CXX object src/browser/CMakeFiles/keepassxcbrowser.dir/HostInstaller.cpp.obj
C:/msys64/home/cstocker/download/keepassxc/src/browser/HostInstaller.cpp: In member function 'QString HostInstaller::getInstallDir(HostInstaller::SupportedBrowsers) const':
C:/msys64/home/cstocker/download/keepassxc/src/browser/HostInstaller.cpp:152:56  error: unused parameter 'browser' [-Werror=unused-parameter]
 QString HostInstaller::getInstallDir(SupportedBrowsers browser) const
                                                        ^~~~~~~
cc1plus.exe: all warnings being treated as errors
make[2]: *** [src/browser/CMakeFiles/keepassxcbrowser.dir/build.make:231: src/browser/CMakeFiles/keepassxcbrowser.dir/HostInstaller.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:607: src/browser/CMakeFiles/keepassxcbrowser.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
`

## Possible Solution
None at this time

## Steps to Reproduce (for bugs)

1. Utilized this guide to set up my build environment"https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows" 
2. Added the following required package "pacman -Sy mingw-w64-x86_64-libsodium" might want to add this to your dependency needs
3. dowloaded the keepassxc-browser branch
4. made the build directory inside root as indicated
5. used the following cmake command "cmake -DWITH_TESTS=OFF -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_BROWSER=ON -DWITH_XC_SSHAGENT=ON -G "MSYS Makefiles" .."
6. issued "make package"

Operating system: Windows 10 Pro, latest patches
CPU architecture: x686 64 bit
Kernel: windows

Enabled extensions:
- Browser
- HTTP
- Autotype
- SSHAgent

**Comment by varjolintu** [comment]
Fixed.

**Comment by iceman73** [comment]
TU
