### ISSUE TITLE
Keepassxc is now prompting to confirm browser access repeatedly, even on pages where there is no login form

### ISSUE THREAD

**Issue by Isles487** [varjolintu/keepassxc#22]
## Expected Behavior
Keepassxc should prompt for access to credentials only on pages where there is a login form. 

## Current Behavior
Now, it does it even on pages without a login form.

## Steps to Reproduce (for bugs)

1. Do not check "never ask before accessing credentials" in Keepassxc. 
2. Allow credentials from keepass to be used to log in. Do not hit "remember" checkbox
3.  Keepassxc will prompt for login on many page loads or switching back to the tab, even when there is no user ID and password field. 

## Debug Info
Using keepassxc-proxy (latest)

KeePassXC - Version 2.2.4
Revision: 9c641dd

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.2

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)

Using keepassxc browser in firefox, updated on 1/22/18 (0.5.0).

**Comment by ezeeyahoo** [comment]
same with Chromium extension. How to go back to older browser extension?

**Comment by varjolintu** [comment]
I can reproduce this. Fixing it right away.

**Comment by varjolintu** [comment]
Fixed with new release 0.5.1. Please update and test.

**Comment by Isles487** [comment]
I can confirm that this issue is fixed, thanks. I just wanted to add, when the user has not hit "remember," and visits a page, keepassxc will prompt once for authorization, but in order to fill the username/password fields, the user will have to then to right click, choose to fill username and password, at which point keepassxc will once again prompt for authorization before filling the fields- is this the intended behavior?

**Comment by varjolintu** [comment]
@Isles487 When prompting for the authorization for the first time and accepting it the credentials are received and there shouldn't be a second confirmation. If you deny the prompt when loading the page then the confirmation popup will be shown again when you choose to fill the username/password.

Please notice that auto-filling is disabled by default. An user interaction is required: use the autocomplete menu on the input field or the keyboard shortcut.

**Comment by Isles487** [comment]
If I go to obsrv.org login page, I am prompted for my credentials and hit accept - when I click on the username field, I am presented with a list of usernames, but it seems to be firefox's feature, not keepass. So when I right click and select "fill username and password" in the keepass context menu, it once again prompts me for access to credentials.

**Comment by varjolintu** [comment]
It's a known issue that WebExtension don't work well together with the Firefox's internal password manager. You could try to disable it.

**Comment by Isles487** [comment]
Interesting. The user names field populates with some suggested usernames even though I am not using FF to store any passwords.

Do you need me to close this?

**Comment by varjolintu** [comment]
Have you got "Remember search and form history" enabled in about:preferences#privacy? That probably explains it.

You can close this after you have confirmed everything works like it should.
