### ISSUE TITLE
CacDialog

### ISSUE THREAD

**Issue by mauron85** [varjolintu/keepassxc#3]
Me again ;-)

Working on browser extensions, I found out that Cancel/Deny action on modal dialogs doesn't generate any response.

## Expected Behavior

Cancel/Deny actions in KeePassXC dialogs like association new database or dialog confirming access to credentials should IMO generate response. The reason is to distinguish between situation, when app is not running and therefor request should timeout after some milliseconds and situation where we're waiting for user action.

## Current Behavior

To express this in pseudo code: 

First case: Send request via NativeClient to get opened db hash. Response will timeout if app is not running.

```
port.postMessage({ type: GET_DB_HASH }); //send request via NativeClient
// now wait for response or timeout after 3secs
const { response, timeout } = yield race({
  response: take(message.action),
  timeout: call(delay, 3000)
});
if (timeout) {
  throw new Error('Response timeout');
}
```

This case is just fine. If NativeClient doesn't receive response in give timeframe, it's considered as error and application flow continue normally.

Second case: Send association request via NativeClient. Response cannot be timeouted as we're waiting for user to confirm or deny request.

```
port.postMessage({ type: ASSOCIATE }); //send request via NativeClient
// we cannot simply timeout request as in previous case or also we cannot send/receive any new messages as it may cause interleaved (out of order) responses.
```

## Possible Solution

If keepassxc sends response also in case of user denial/cancel dialog request, we can handle this situation properly.

**Comment by varjolintu** [comment]
You again! (But hey, I've seen what you have done and I like it. Even if you removed the fork text ;)

Thanks for the tip. If you cancel association a following error reply will be sent:
```
{
"action": <action>,
"errorCode": 6,
"error": "Action cancelled or denied"
}
```

Returning an error reply from denying access to a credentials is a more complex thing. If you have several entries to one page and for example three of them are already accepted but the fourth one denied when entering the page, you cannot reply an error because those three entries are still valid. If you have only one entry you could always return an error when the user list is empty but that would cause errors on any site that doesn't have any corresponding credentials.

I'm not even sure if you *must* return an error if an access to single entry is denied. Where would you display that error anyway?

If you have any suggestions, they are always welcome :)

**Comment by mauron85** [comment]
>Even if you removed the fork text ;)

no worries, you'll be specially credited in README.md when I'm done. :-) And yes I have removed fork notice (actually created new repo), as there is not much left from the passifox (except some libs and function calls related to old KeePassHTTP protocol - and those libs are using global vars, so I even had to modified them to work). Anyway I will credit you more for your work, because after implementing HTTP protocol I see how not great it is comparing to yours. If I'm not wrong they're using encryption key, which is stored in browser localStorage and I believe that key can be theoretically captured (at least with tcpdump), from initial plugin to keepassxc app conversation and later directly from browser localStorage (but I might be wrong here). Your solution is much better as you're using public/private keys on both sides. Also you're encrypting whole payload, they're not. Payload (json) structure is fully readable (actual data are not). Good job.

**Comment by mauron85** [comment]
>If you have several entries to one page and for example three of them are already accepted but the fourth one denied when entering the page, you cannot reply an error because those three entries are still valid.

Didn't know this is possible. Is it really implemented? Because I just gave suggestion for improvement, which is kind of related to this. https://github.com/keepassxreboot/keepassxc/issues/769

**Comment by mauron85** [comment]
>I'm not even sure if you must return an error if an access to single entry is denied. Where would you display that error anyway?


I didn't do good job explaining, why I consider this necessary. The problem is, that I don't want to make NativeClient (proxy) too complex, but still want to make it as reliable as possible.
I don't really want to allow parallel execution of commands in messaging system like NaCL which is using input/output stream, as it will be difficult to match response to request (they may come out of order.) I mean, it's doable, but probably it will require to add Id to each request and on app side add same Id for each response (or something like that).

My approach is that execution of actions is serial. Action has to finish (response from app has to be received or request has to be timeouted), before any new action can start. It's not perfect, but I'm confident with it. Also request buffer can be easily added.

I used ES6 generators (redux-saga), which allows you to pause execution in middle of function and wait for some action before continuing with the execution. The relevant piece of code [is here](https://github.com/mauron85/keepassxc-browser/blob/master/src/background/sagas/nativeClient.ts). Basically what it does, is on some action (associate, getDBHash, ...) it will post message to native client (`port.postMessage`) and waits for response or timeout from native client (saga channel) and return result to the caller. From caller perspective it looks like [normal function call](https://github.com/mauron85/keepassxc-browser/blob/master/src/background/keepass/keepassNaCl.ts#L129).

But problem is that, those requests waiting for user interaction should not be time-outed, because it will be awkward to the user. I didn't saw any problem, until you mentioned `access to single entry is denied.`
Need to rethink whole thing, but maybe it doesn't change anything as I'm only interested in response and not about payload the response holds. In other words any response is ok.

**Comment by varjolintu** [comment]
> If I'm not wrong they're using encryption key, which is stored in browser localStorage and I believe that key can be theoretically captured (at least with tcpdump), from initial plugin to keepassxc app conversation and later directly from browser localStorage (but I might be wrong here). Your solution is much better as you're using public/private keys on both sides. Also you're encrypting whole payload, they're not. Payload (json) structure is fully readable (actual data are not).

Yes. The chromeIPass/PassIFox works that way. So it uses the same key every time, and the same key is always transferred to KeePassXC. And it's the only key that's being used for encryption/decryption. In my implementation the public key used to associate the browser extension is saved with the ID to localStorage (a new key pair is always generated for each connection for encrypting the actual data). And there's the one problem I haven't solved yet. Basically, if you can read the browser's localStorage, you can get the ID and corresponding public key and use the UDP port proxy implementation to get credentials without any user interaction.. maybe a simple Python script could do that (actually I might even try the method). So there's lot to do with the current implementation to make it more secure. But well, to get the credentials with that method, someone has to get access to your computer, your database must be open etc. Still, I would like to make it more secure somehow. Just don't know yet how.

> My approach is that execution of actions is serial. Action has to finish (response from app has to be received or request has to be timeouted), before any new action can start. It's not perfect, but I'm confident with it. Also request buffer can be easily added.

My approach is fully asynchronous, although it lacks a buffer. My opinion is that if you are using a proxy application it should be responsible for returning a correct reply (the proxy application is active all the time even when KeePassXC isn't). If you are using the browser extension straight with KeePassXC there's always a response available, and the extension also detects if KeePassXC is not opened or database is closed.
