### ISSUE TITLE
Application icons missing when building AppImage with release-tool using docker container

### ISSUE THREAD

**Issue by mauron85** [varjolintu/keepassxc#4]
When running KeePassXC AppImage built using release tool, app is missing icons in toolbar and text placeholders are displayed instead.

![28223961-ad30d3f2-68cd-11e7-880a-e63b855a8d10](https://user-images.githubusercontent.com/359450/28239824-01ac3a64-6975-11e7-8b89-44903a37e651.png)

## Steps to Reproduce (for bugs)

1. start with clean directory (warning this will remove all custom files)
`git clean -fdx`
2. create new branch with starting point feature/chromeKeePassXC
`git checkout -b release/2.2.0-browser-beta5 feature/chromeKeePassXC`
3. merge latest release-tool, where origin is https://github.com/keepassxreboot/keepassxc (read [discussion](https://github.com/keepassxreboot/keepassxc/issues/39) why)
`git checkout origin/develop -- ./release-tool`
`git add -u`
`git commit -m "merging latest release-tool"`
4. build docker image from following Dockerfile:
```
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install --yes build-essential cmake libxi-dev libxtst-dev qtbase5-dev \
    libqt5x11extras5-dev qttools5-dev qttools5-dev-tools \
    libgcrypt20-dev zlib1g-dev libyubikey-dev libykpers-1-dev \
    libsodium-dev libboost-system-dev \
    python-pip git wget fuse module-init-tools

RUN pip install transifex-client

VOLUME /keepassxc/src
VOLUME /keepassxc/out
WORKDIR /keepassxc
```
`docker build -t keepassxc .`
5. build AppImage
`./release-tool build -p "browser http" -v 2.2.0-browser-beta5 -d keepassxc`
6. run AppImage
7. icons are not shown in toolbar

**Interestingly** icons are displayed when build is done with only `http` plugin, but again dir must be cleaned with `git clean -fdx` as it seems plugin configuration cannot be changed after first build. Bug?
`./release-tool build -p "http" -v 2.2.0-browser-beta5 -d keepassxc`

I've tried to figure out why, this is happening comparing with origin/develop branch, but didn't found any significant difference in configuration files.

**Comment by varjolintu** [comment]
Gotta investigate this with my Linux box. I guess this is related to #2.

**Comment by mauron85** [comment]
No problem. This is normal in this stage. The strange thing is that icons are shown when only http plugin is built, which is bit of mystery for me. Also I had to use my own Dockerfile (even though using Ubuntu 16.04 is not recommended by KeePassXC guys), because I was racing two kinds of build errors:

`./release-tool build -p "autokey http" -v 2.2.0-browser-beta5 -d keepassxc/ubuntu:14.04`

On first build (clean dir):
```
Building CXX object src/http/CMakeFiles/keepasshttp.dir/Protocol.cpp.o
/keepassxc/src/src/http/AccessControlDialog.cpp:20:36: fatal error: ui_AccessControlDialog.h: No such file or directory
 #include "ui_AccessControlDialog.h"
                                    ^
compilation terminated.
/keepassxc/src/src/http/HttpPasswordGeneratorWidget.cpp:20:44: fatal error: ui_HttpPasswordGeneratorWidget.h: No such file or directory
 #include "ui_HttpPasswordGeneratorWidget.h"
                                            ^
compilation terminated.
/keepassxc/src/src/http/OptionDialog.cpp:20:29: fatal error: ui_OptionDialog.h: No such file or directory
 #include "ui_OptionDialog.h"
                             ^
compilation terminated.
make[2]: *** [src/http/CMakeFiles/keepasshttp.dir/AccessControlDialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/http/CMakeFiles/keepasshttp.dir/HttpPasswordGeneratorWidget.cpp.o] Error 1
make[2]: *** [src/http/CMakeFiles/keepasshttp.dir/OptionDialog.cpp.o] Error 1
In file included from /opt/qt58/include/QtCore/QtCore:4:0,
                 from /keepassxc/src/src/http/Protocol.h:22,
                 from /keepassxc/src/src/http/Protocol.cpp:19:
/keepassxc/src/src/http/Protocol.cpp: In function 'QByteArray encrypt2(const QByteArray&, SymmetricCipherGcrypt&)':
/opt/qt58/include/QtCore/qglobal.h:669:28: warning: ignoring return value of function declared with attribute warn_unused_result [-Wunused-result]
 #define Q_UNUSED(x) (void)x;
                            ^
/keepassxc/src/src/http/Protocol.cpp:119:5: note: in expansion of macro 'Q_UNUSED'
     Q_UNUSED(cipher.processInPlace(buffer));
     ^
make[1]: *** [src/http/CMakeFiles/keepasshttp.dir/all] Error 2
make: *** [all] Error 2
[ ERROR ] Docker build failed!
```

Or the other one:
```
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.55 (or
  newer).
Call Stack (most recent call first):
  src/browser/CMakeLists.txt:4 (find_package)


CMake Warning (dev) at src/browser/CMakeLists.txt:15 (find_package):
  Syntax Warning in cmake code at

    /keepassxc/src/cmake/Findsodium.cmake:85:57

  A future version of CMake may treat unquoted argument:

    [=[

  as an opening long bracket.  Double-quote the argument.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by mauron85** [comment]
In my case there are icons in Setttings window:

![image](https://user-images.githubusercontent.com/359450/28240319-dd3b3a9e-697f-11e7-972b-05c9048e597c.png)

Also running from terminal prints out following:

```
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
FilePath::DataPath: can't find data dir
Couldn't load passphrase wordlist.
Couldn't load translations.
Couldn't load passphrase wordlist.
Couldn't load passphrase wordlist.
QSystemTrayIcon::setVisible: No Icon set
Couldn't load passphrase wordlist.
Couldn't load passphrase wordlist.
```

**Comment by varjolintu** [comment]
This is a quite interesting bug. Some things I tried before when I encountered the `QCoreApplication::applicationDirPath: Please instantiate the QApplication object first` error was to try launching KeePassXC with sudo. Could you try if that makes any difference? And what's the output of terminal when you have a version without browser extension support?

Edit: I reproduced the issue. Going to investigate it more when I have time. Running the executable with root permissions didn't help.

**Comment by mauron85** [comment]
Yep, sudo actually made it worse. No icons at all. :-)

**Comment by mauron85** [comment]
>And what's the output of terminal when you have a version without browser extension support?

Just tried again to compile and run app with just `http` plugin support:
`./release-tool build -p "http" -v 2.2.0-browser-beta5 -d keepassxc`

When running from terminal, it doesn't generate any error (no output at all and app just starts and icons are loaded). Super strange.

**Comment by varjolintu** [comment]
I have a hunch this is related to Boost or libsodium libraries (just don't know how, maybe initializing them in the constructor? Those are also launched and initialized in gui/MainWindow.cpp). I think I'll make some tests where I just disable all boost/libsodium-related code and linkings.

That is: when I have time :)

**Comment by varjolintu** [comment]
Duplicate issue with #2.
