### ISSUE TITLE
Need help with connecting keepassxc-browser

### ISSUE THREAD

**Issue by Lalarian** [varjolintu/keepassxc#5]
Hello!

I'm new to Keepass in general.
I tried your release first, because it's the most recent and seems promising.

## Expected Behavior
I also have installed your firefox AddOn keepassxc-browser and want to use it for saving and filling passwords on web sites.

## Current Behavior
I have successfully build your keypassxc frok on Xubuntu 17.04. I opened the GUI, created a databse and added some test passwords.
But: The Firefox AddOn tells me:

> keepassxc-browser has encountered an error:
> 
> Timeout or not connected to KeePassXC 

## Possible Solution
I think I need to configure the AddOn somehow. I had a look at the settings, but in the AddOn's settings I only see:

> No connected databases found.

It's all latest version.

## Debug Info

KeePassXC - Version 2.2.0
Revision: bcc00018785824bf267c6ca54ae94049b1a85379

Bibliotheken:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Betriebssystem: Ubuntu 17.04
CPU-Architektur: x86_64
Kernel: linux 4.10.0-32-generic

Aktivierte Erweiterungen: None

Libraries:
- LIBS

Operating system: Xubuntu 17.04
CPU architecture: x86_64
Kernel: 4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Enabled extensions:
none

Thank you :)

**Comment by varjolintu** [comment]
Please see this new [wiki page](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-current-beta-build) and see if it's any help :)

**Comment by Lalarian** [comment]
There we got my first mistake:
I've simply build with a makefile using the options you have given as example in the README.
(cmake -DWITH_TESTS=OFF ..)

So my build doesn't even have  browser integration settings.
I'm now at trying to make a new build, using a makefile created with:
cmake -DWITH_XC_BROWSER=ON -DWITH_XC_HTTP=ON -DWITH_ASAN=ON ..

But at the moment I'm stuck at some missing headers problem.
I have installed libboost-dev and all the other dependencies cmake was asking for. Cmake passed without errors.

`[100%] Linking CXX executable keepassxc
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::HttpPlugin(DatabaseTabWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:73: Nicht definierter Verweis auf `Service::Service(DatabaseTabWidget*)'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::BrowserPlugin(DatabaseTabWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:119: Nicht definierter Verweis auf `ChromeListener::ChromeListener(DatabaseTabWidget*)'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `OptionDialog* qobject_cast<OptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `OptionDialog::staticMetaObject'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::saveSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:103: Nicht definierter Verweis auf `OptionDialog::saveSettings()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:104: Nicht definierter Verweis auf `HttpSettings::isEnabled()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:107: Nicht definierter Verweis auf `KeepassHttpProtocol::Server::stop()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:105: Nicht definierter Verweis auf `KeepassHttpProtocol::Server::start()'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `OptionDialog* qobject_cast<OptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `OptionDialog::staticMetaObject'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::loadSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:98: Nicht definierter Verweis auf `OptionDialog::loadSettings()'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::createWidget()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:90: Nicht definierter Verweis auf `OptionDialog::OptionDialog(QWidget*)'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserOptionDialog* qobject_cast<BrowserOptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `BrowserOptionDialog::staticMetaObject'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::saveSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:150: Nicht definierter Verweis auf `BrowserOptionDialog::saveSettings()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:151: Nicht definierter Verweis auf `BrowserSettings::isEnabled()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:154: Nicht definierter Verweis auf `ChromeListener::stop()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:152: Nicht definierter Verweis auf `ChromeListener::run()'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserOptionDialog* qobject_cast<BrowserOptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `BrowserOptionDialog::staticMetaObject'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::loadSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:145: Nicht definierter Verweis auf `BrowserOptionDialog::loadSettings()'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::createWidget()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:137: Nicht definierter Verweis auf `BrowserOptionDialog::BrowserOptionDialog(QWidget*)'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:221: Nicht definierter Verweis auf `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:222: Nicht definierter Verweis auf `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: Nicht definierter Verweis auf `boost::system::system_category()'
../libkeepassx_core.a(MainWindow.cpp.o): In Funktion `boost::asio::error::get_system_category()':
/usr/include/boost/asio/error.hpp:230: Nicht definierter Verweis auf `boost::system::system_category()'
../libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `operator()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/EditWidgetIcons.cpp:180: Nicht definierter Verweis auf `qhttp::QHttpAbstractInput::end()'
../libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `connect<void (qhttp::QHttpAbstractInput::*)(), EditWidgetIcons::fetchFavicon(const QUrl&)::<lambda(qhttp::client::QHttpResponse*)>::<lambda()> >':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:324: Nicht definierter Verweis auf `qhttp::QHttpAbstractInput::staticMetaObject'
../libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `qhttp::client::QHttpClient::request(qhttp::THttpMethod, QUrl, std::function<void (qhttp::client::QHttpResponse*)> const&)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/http/qhttp/qhttpclient.hpp:71: Nicht definierter Verweis auf `qhttp::client::QHttpClient::request(qhttp::THttpMethod, QUrl, std::function<void (qhttp::client::QHttpRequest*)> const&, std::function<void (qhttp::client::QHttpResponse*)> const&)'
../libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `setConnectingTimeOut<EditWidgetIcons::fetchFavicon(const QUrl&)::<lambda()> >':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/http/qhttp/qhttpclient.hpp:112: Nicht definierter Verweis auf `qhttp::client::QHttpClient::setConnectingTimeOut(unsigned int)'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/http/qhttp/qhttpclient.hpp:112: Nicht definierter Verweis auf `qhttp::client::QHttpClient::connectingTimeOut()'
../libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `connect<void (qhttp::client::QHttpClient::*)(), EditWidgetIcons::fetchFavicon(const QUrl&)::<lambda()> >':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:324: Nicht definierter Verweis auf `qhttp::client::QHttpClient::staticMetaObject'
../libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `EditWidgetIcons::fetchFavicon(QUrl const&)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/EditWidgetIcons.cpp:172: Nicht definierter Verweis auf `qhttp::client::QHttpClient::QHttpClient(QObject*)'
../libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `operator()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/EditWidgetIcons.cpp:182: Nicht definierter Verweis auf `qhttp::client::QHttpResponse::status() const'
collect2: error: ld returned 1 exit status
src/cli/CMakeFiles/keepassxc-cli.dir/build.make:133: die Regel für Ziel „src/cli/keepassxc-cli“ scheiterte
make[2]: *** [src/cli/keepassxc-cli] Fehler 1
CMakeFiles/Makefile2:593: die Regel für Ziel „src/cli/CMakeFiles/keepassxc-cli.dir/all“ scheiterte
make[1]: *** [src/cli/CMakeFiles/keepassxc-cli.dir/all] Fehler 2
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::HttpPlugin(DatabaseTabWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:73: Nicht definierter Verweis auf `Service::Service(DatabaseTabWidget*)'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::BrowserPlugin(DatabaseTabWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:119: Nicht definierter Verweis auf `ChromeListener::ChromeListener(DatabaseTabWidget*)'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `OptionDialog* qobject_cast<OptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `OptionDialog::staticMetaObject'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::saveSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:103: Nicht definierter Verweis auf `OptionDialog::saveSettings()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:104: Nicht definierter Verweis auf `HttpSettings::isEnabled()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:107: Nicht definierter Verweis auf `KeepassHttpProtocol::Server::stop()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:105: Nicht definierter Verweis auf `KeepassHttpProtocol::Server::start()'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `OptionDialog* qobject_cast<OptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `OptionDialog::staticMetaObject'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::loadSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:98: Nicht definierter Verweis auf `OptionDialog::loadSettings()'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `HttpPlugin::createWidget()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:90: Nicht definierter Verweis auf `OptionDialog::OptionDialog(QWidget*)'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserOptionDialog* qobject_cast<BrowserOptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `BrowserOptionDialog::staticMetaObject'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::saveSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:150: Nicht definierter Verweis auf `BrowserOptionDialog::saveSettings()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:151: Nicht definierter Verweis auf `BrowserSettings::isEnabled()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:154: Nicht definierter Verweis auf `ChromeListener::stop()'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:152: Nicht definierter Verweis auf `ChromeListener::run()'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserOptionDialog* qobject_cast<BrowserOptionDialog*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:495: Nicht definierter Verweis auf `BrowserOptionDialog::staticMetaObject'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::loadSettings(QWidget*)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:145: Nicht definierter Verweis auf `BrowserOptionDialog::loadSettings()'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `BrowserPlugin::createWidget()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/MainWindow.cpp:137: Nicht definierter Verweis auf `BrowserOptionDialog::BrowserOptionDialog(QWidget*)'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:221: Nicht definierter Verweis auf `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:222: Nicht definierter Verweis auf `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: Nicht definierter Verweis auf `boost::system::system_category()'
libkeepassx_core.a(MainWindow.cpp.o): In Funktion `boost::asio::error::get_system_category()':
/usr/include/boost/asio/error.hpp:230: Nicht definierter Verweis auf `boost::system::system_category()'
libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `operator()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/EditWidgetIcons.cpp:180: Nicht definierter Verweis auf `qhttp::QHttpAbstractInput::end()'
libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `connect<void (qhttp::QHttpAbstractInput::*)(), EditWidgetIcons::fetchFavicon(const QUrl&)::<lambda(qhttp::client::QHttpResponse*)>::<lambda()> >':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:324: Nicht definierter Verweis auf `qhttp::QHttpAbstractInput::staticMetaObject'
libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `qhttp::client::QHttpClient::request(qhttp::THttpMethod, QUrl, std::function<void (qhttp::client::QHttpResponse*)> const&)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/http/qhttp/qhttpclient.hpp:71: Nicht definierter Verweis auf `qhttp::client::QHttpClient::request(qhttp::THttpMethod, QUrl, std::function<void (qhttp::client::QHttpRequest*)> const&, std::function<void (qhttp::client::QHttpResponse*)> const&)'
libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `setConnectingTimeOut<EditWidgetIcons::fetchFavicon(const QUrl&)::<lambda()> >':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/http/qhttp/qhttpclient.hpp:112: Nicht definierter Verweis auf `qhttp::client::QHttpClient::setConnectingTimeOut(unsigned int)'
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/http/qhttp/qhttpclient.hpp:112: Nicht definierter Verweis auf `qhttp::client::QHttpClient::connectingTimeOut()'
libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `connect<void (qhttp::client::QHttpClient::*)(), EditWidgetIcons::fetchFavicon(const QUrl&)::<lambda()> >':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:324: Nicht definierter Verweis auf `qhttp::client::QHttpClient::staticMetaObject'
libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `EditWidgetIcons::fetchFavicon(QUrl const&)':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/EditWidgetIcons.cpp:172: Nicht definierter Verweis auf `qhttp::client::QHttpClient::QHttpClient(QObject*)'
libkeepassx_core.a(EditWidgetIcons.cpp.o): In Funktion `operator()':
/home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/gui/EditWidgetIcons.cpp:182: Nicht definierter Verweis auf `qhttp::client::QHttpResponse::status() const'
collect2: error: ld returned 1 exit status
src/CMakeFiles/keepassxc.dir/build.make:132: die Regel für Ziel „src/keepassxc“ scheiterte
make[2]: *** [src/keepassxc] Fehler 1
CMakeFiles/Makefile2:184: die Regel für Ziel „src/CMakeFiles/keepassxc.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/keepassxc.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
`

Your header files seem to be where they are supposed to:
i.e. /home/ladmin/Downloads/keepassxc-2.2.0-browser-beta8/src/http/qhttp/qhttpclientresponse.hpp

Sorry, I'm not so experienced at building, yet :(

**Comment by varjolintu** [comment]
If you followed the build instructions from [here](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) you can always try to delete the build directory and make a new one.

If you want to build fork correctly, please do these steps after cloning the repository:
`git checkout feature/chromeKeePassXC`
`git fetch && git pull`

You can also try to build the release without HTTP support:
`cmake -DWITH_TESTS=OFF -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=OFF -DWITH_XC_BROWSER=ON -DCMAKE_BUILD_TYPE=Release ..`

**Comment by Lalarian** [comment]
Honestly I'm not even sure, whether I need http support. What I need is the Firefox-Addon working. If the browser module only is enough for this, than I'll try building without http support again.

**Comment by Lalarian** [comment]
Thank you again! :)

I just did:
git checkout feature/chromeKeePassXC
git fetch && git pull

and installed following libraries as said at "normal" keepassxc instructions:
```
qtbase
qttools5
libgcrypt
zlib
libxi
libxtst
qtx11extras
```

Build was successfull now, including http and everything else! Also the browser AddOn is connected.

_Btw. I'm using Waterfox, because it's MUCH faster than Firefox and Firefox is about to die for me as soon as they are dropping AddOn support, while Waterfox will keep up AddOn support. Maybe you could add the option for supporting Waterfox's new configuration path natively (~/.waterfox/)? I have made it working by copying the json file from Firefox to Waterfox._

**Only problem is, that my apt-get wants to auto remove a whole bunch of packages since I installed
"qtbase5-dev" and "qtbase5-dev-tools".**

```
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  libqt5xmlpatterns5 mencoder python-apptools python-attr python-autobahn python-cbor python-cffi python-click python-colorama
  python-concurrent.futures python-constantly python-envisage python-incremental python-lz4 python-mpi4py python-msgpack python-nacl
  python-pam python-ply python-pyasn1-modules python-pycparser python-qrcode python-serial python-service-identity python-snappy
  python-trollius python-twisted python-twisted-bin python-twisted-core python-txaio python-zope.interface python3-sip
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
```

**I hope this won't make my system unusable after rebooting..**

**Comment by varjolintu** [comment]
Glad you got the extension working :) I will investigate the plugin on Waterfox. I'm not sure if it's necessary to support every possible browser when installing the manifest files. The apt-get autoremove thing you must solve by yourself, sorry. Closing the issue.

**Comment by killua99** [comment]
Sorry to write in here, but, I also use waterfox, there is a chance to build an easy way to tell where the path is?

You could follow this post: https://www.waterfoxproject.org/blog/waterfox-55.0-release-download to get more info about waterfox.

But if in the settings UI there is a fuild to tell where is my path and database.

**Comment by varjolintu** [comment]
Try to move the com.varjolintu.keepassxc_browser.json file from `./mozilla/native-messaging-hosts/` to `./waterfox/native-messaging-hosts/`?

**Comment by Lalarian** [comment]
Hello!
I think I should add, that in between I found out, that moving or copying the file isn't needed for Waterfox.
It's working fine with the file at '~/.mozilla/native-messaging-hosts/com.varjolintu.keepassxc_browser.json'.

But maybe the file isn't installed at all, if the .mozilla directory doesn't exist in a user's home?

I exactly know how or why it is working with .mozilla path, but maybe it's related to my Waterfox configuration having been migrated from the genuine Firefox configuration at .mozilla some versions ago, when Waterfox made the transition from using .mozilla to using it's own .waterfox path.

**Comment by varjolintu** [comment]
Have you installed the browser support? Here's a [guide](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-current-beta-build).

**Comment by killua99** [comment]
how do I install browser support? should I compile it?

**Comment by varjolintu** [comment]
@killua99 [https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC)

If you download the sources. Do the following before cmake and compiling:
`git checkout feature/chromeKeePassXC`
`git fetch && git pull`

Or download a release from [here](https://github.com/varjolintu/keepassxc/releases)

**Comment by varjolintu** [comment]
And please.. no more non-relevant questions to this thread.

**Comment by killua99** [comment]
I, hope I don't get annoying, I'm trying my best to don't write non-relevant questions, I do understand that matter on OSS, I also maintain packages and I do know how annoying some questions could be.

I'm writing down this to prove some feed back in order to help or contribute to have this feature inbuild in the future of KeePassXC 2.3.0.

The thing is the `make -j8 package` is failing. The current log is at. https://gist.github.com/killua99/50f973c31f29692a4db0c1b00b455ea1

I'm not just trying with Waterfox btw, Chrome also fails to connect to the database.

I'm on macOS 10.12.6

I did follow the instruction to compile KeePassXC on macOS, this was the command I did use.

    cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release \
      -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON \
      -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.9.1/lib/cmake ..

    make -j8 pckage

Hope I did help to provide more feedback for this issue.

**Comment by varjolintu** [comment]
Check the feature branch [README](https://github.com/varjolintu/keepassxc/tree/feature/chromeKeePassXC). You forgot the only option you need: `-DWITH_XC_BROWSER=ON`.

Also, the instructions are here just a few messages [earlier](https://github.com/varjolintu/keepassxc/issues/5#issuecomment-324903967).

**Comment by Lalarian** [comment]
Problem was same for me back then. I think it's because of this paragraph:
`Once you have downloaded the source code, you can cd into the source code directory, build and install KeePassXC:

mkdir build
cd build
cmake -DWITH_TESTS=OFF ..
make -j8
sudo make install`

It doesn't say example and everyone expects browser support as the main feature, so no one reads any further at first.

I think if you changed the example at this position so that it included "-DWITH_XC_BROWSER=ON" you wouldn't have to answer the same question over and over. :)

**Comment by varjolintu** [comment]
@Lalarian This README is identical with the official one. Only Auto-Type option is enabled by default. And you can see the options listing right after.

I upgraded the develop branch (default) to include the same README so it's always seen without the need of changing to the extension branch.

Browser extension is disabled by default just like the HTTP implementation. One good reason for this is that the browser extension feature need additional dependencies (Boost and libsodium).
