### ISSUE TITLE
Firefox Plugin Notification: You use an old version of KeePassXC. 

### ISSUE THREAD

**Issue by ahmedelz** [varjolintu/keepassxc#7]
I'm using the KeepassXC browser plugin for Firefox. I downloaded KeepassXC 2.2.0-browser-rc2 from GitHub few days ago. Today, the browser plugin is showing this notification:

> You use an old version of KeePassXC.
> Please download the latest version from keepassxc.org. 

It seems that KeePass has released a newer version: 2.2.1. Are you planning to merge the code changes to the main/official KeePassXC release streams?

Operating system: Mac OS Sierra 10.12.6
Firefox 57.0b5 (64-bit)

**Comment by varjolintu** [comment]
Yes, I'm going to do that when I have the time. Maybe first to a separate branch.

**Comment by Lalarian** [comment]
Does this mean you won't be updating here anymore from then on?

**Comment by varjolintu** [comment]
You'll get the updates. Don't worry :)

**Comment by varjolintu** [comment]
At this point it seems I'm waiting for the 2.2.2 release before merging anything. It should be released soon.
